"""
DataWise AI — Production FastAPI Inference Service Code Generator
Generates a standalone, runnable FastAPI application (api/main.py) for the trained pipeline.
Endpoints:
  - GET /health
  - GET /model-info
  - POST /predict (single record JSON)
  - POST /predict_batch (CSV or JSON array)
"""

from typing import Any, Dict, List


class FastAPIServiceGenerator:
    """Generates a standalone, production-ready FastAPI inference microservice."""

    @staticmethod
    def generate_code(
        feature_names: List[str],
        target_name: str,
        task_type: str,
        model_name: str,
        version: str = "1.0.0",
    ) -> str:
        schema_fields = "\n".join([f"    {f.replace(' ', '_').replace('-', '_')}: Any" for f in feature_names])
        field_mapping = ",\n".join([f'        "{f}": payload.{f.replace(" ", "_").replace("-", "_")}' for f in feature_names])

        code = f'''"""
DataWise AI — Production Model Inference Service
Autonomous FastAPI Microservice for {model_name}
Generated by DataWise AI Platform
"""

import os
import json
import joblib
import pandas as pd
from typing import Any, Dict, List, Optional
from fastapi import FastAPI, HTTPException, UploadFile, File, status
from pydantic import BaseModel
import io

app = FastAPI(
    title="DataWise AI — {model_name} Inference API",
    description="Production inference endpoint for automated ML pipeline predicting '{target_name}'",
    version="{version}",
)

# Load pipeline at module import
MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "final_model.joblib")
METADATA_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "model_metadata.json")

pipeline = None
metadata = {{}}

try:
    if os.path.exists(MODEL_PATH):
        pipeline = joblib.load(MODEL_PATH)
    elif os.path.exists("final_model.joblib"):
        pipeline = joblib.load("final_model.joblib")
    
    if os.path.exists(METADATA_PATH):
        with open(METADATA_PATH, "r") as f:
            metadata = json.load(f)
except Exception as e:
    print(f"Warning: Could not load model pipeline at startup: {{e}}")


class PredictionInput(BaseModel):
{schema_fields}


class PredictionResponse(BaseModel):
    prediction: Any
    probability: Optional[List[float]] = None
    model_name: str = "{model_name}"
    version: str = "{version}"
    status: str = "success"


class BatchPredictionResponse(BaseModel):
    row_count: int
    predictions: List[Any]
    probabilities: Optional[List[List[float]]] = None
    status: str = "success"


@app.get("/health", tags=["System"])
def health_check():
    return {{
        "status": "healthy",
        "model_loaded": pipeline is not None,
        "model_name": "{model_name}",
        "version": "{version}",
    }}


@app.get("/model-info", tags=["Metadata"])
def get_model_info():
    return {{
        "model_name": "{model_name}",
        "target": "{target_name}",
        "task_type": "{task_type}",
        "features": {feature_names},
        "metadata": metadata,
    }}


@app.post("/predict", response_model=PredictionResponse, tags=["Inference"])
def predict(payload: PredictionInput):
    if pipeline is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Model pipeline is not loaded.",
        )
    
    # Construct DataFrame with original feature names
    data = pd.DataFrame([{{
{field_mapping}
    }}])

    try:
        raw_pred = pipeline.predict(data)[0]
        # Cast numpy types to Python native types
        pred = raw_pred.item() if hasattr(raw_pred, "item") else raw_pred
        probs = None
        if hasattr(pipeline, "predict_proba"):
            try:
                probs = [float(p) for p in pipeline.predict_proba(data)[0]]
            except Exception:
                probs = None

        return PredictionResponse(
            prediction=pred,
            probability=probs,
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Inference error: {{str(e)}}",
        )


@app.post("/predict_batch", response_model=BatchPredictionResponse, tags=["Inference"])
async def predict_batch(file: UploadFile = File(...)):
    if pipeline is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Model pipeline is not loaded.",
        )
    
    contents = await file.read()
    try:
        df = pd.read_csv(io.BytesIO(contents))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid CSV file: {{str(e)}}",
        )

    try:
        raw_preds = pipeline.predict(df)
        preds = [p.item() if hasattr(p, "item") else p for p in raw_preds]
        probs = None
        if hasattr(pipeline, "predict_proba"):
            try:
                raw_probs = pipeline.predict_proba(df)
                probs = [[float(v) for v in row] for row in raw_probs]
            except Exception:
                probs = None

        return BatchPredictionResponse(
            row_count=len(df),
            predictions=preds,
            probabilities=probs,
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Batch prediction error: {{str(e)}}",
        )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
'''
        return code
