"""DataWise AI — SQLAlchemy ORM Models (Bridge & Backward Compatibility Layer)

Re-exports core Base, Session, Dataset, ConversationMessage, Artifact, UserDecision
and all 37 enterprise entities defined in app.db.models.entities.
"""

from __future__ import annotations

from app.db.models.entities import (
    Base,
    LegacySession as Session,
    DatasetEntity as Dataset,
    ConversationMessage,
    ArtifactEntity as Artifact,
    UserDecisionRecord as UserDecision,
    User,
    UserSession,
    ApiKey,
    Project,
    DatasetEntity,
    DatasetVersion,
    DatasetColumn,
    DatasetProfile,
    DataQualityReport,
    Experiment,
    ExperimentRun,
    PreprocessingRun,
    Feature,
    ModelCandidate,
    TrainingRun,
    ModelMetric,
    CrossValidationResult,
    HyperparameterRun,
    EvaluationResult,
    OverfittingReport,
    ExplainabilityResult,
    RobustnessResult,
    ModelEntity,
    ModelVersion,
    ArtifactEntity,
    Notebook,
    Report,
    Deployment,
    PredictionRequest,
    MonitoringMetric,
    DriftReport,
    AgentRun,
    AgentEvent,
    UserDecisionRecord,
    AuditLog,
    BackgroundJob,
    UsageRecord,
    LegacySession,
)

__all__ = [
    "Base",
    "Session",
    "Dataset",
    "ConversationMessage",
    "Artifact",
    "UserDecision",
    "User",
    "UserSession",
    "ApiKey",
    "Project",
    "DatasetEntity",
    "DatasetVersion",
    "DatasetColumn",
    "DatasetProfile",
    "DataQualityReport",
    "Experiment",
    "ExperimentRun",
    "PreprocessingRun",
    "Feature",
    "ModelCandidate",
    "TrainingRun",
    "ModelMetric",
    "CrossValidationResult",
    "HyperparameterRun",
    "EvaluationResult",
    "OverfittingReport",
    "ExplainabilityResult",
    "RobustnessResult",
    "ModelEntity",
    "ModelVersion",
    "ArtifactEntity",
    "Notebook",
    "Report",
    "Deployment",
    "PredictionRequest",
    "MonitoringMetric",
    "DriftReport",
    "AgentRun",
    "AgentEvent",
    "UserDecisionRecord",
    "AuditLog",
    "BackgroundJob",
    "UsageRecord",
    "LegacySession",
]
