"""
Recovery Policies & Configuration
Defines error categories, severities, decision states, standard error codes, and bounded thresholds.
"""

from enum import Enum
from typing import Set

# Core Bounded Limits
MAX_RETRIES: int = 3
MAX_RECOVERY_ATTEMPTS: int = 3
MAX_SAME_ERROR_ATTEMPTS: int = 2
MAX_RECOVERY_TIME_SECONDS: float = 300.0
MAX_COST_BUDGET: float = 5.0

class ErrorCategory(str, Enum):
    TRANSIENT = "TRANSIENT"
    CONFIGURATION = "CONFIGURATION"
    AUTHENTICATION = "AUTHENTICATION"
    AUTHORIZATION = "AUTHORIZATION"
    RATE_LIMIT = "RATE_LIMIT"
    NETWORK = "NETWORK"
    TIMEOUT = "TIMEOUT"
    DATABASE = "DATABASE"
    DATABASE_SCHEMA = "DATABASE_SCHEMA"
    DATA_FORMAT = "DATA_FORMAT"
    DATA_QUALITY = "DATA_QUALITY"
    MISSING_VALUE = "MISSING_VALUE"
    FEATURE_ENGINEERING = "FEATURE_ENGINEERING"
    MODEL_TRAINING = "MODEL_TRAINING"
    MODEL_SERIALIZATION = "MODEL_SERIALIZATION"
    MODEL_INFERENCE = "MODEL_INFERENCE"
    LLM_PROVIDER = "LLM_PROVIDER"
    LLM_QUOTA = "LLM_QUOTA"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    TOOL_FAILURE = "TOOL_FAILURE"
    MCP_FAILURE = "MCP_FAILURE"
    CDC_FAILURE = "CDC_FAILURE"
    STREAM_FAILURE = "STREAM_FAILURE"
    RESOURCE_EXHAUSTION = "RESOURCE_EXHAUSTION"
    MEMORY = "MEMORY"
    CPU = "CPU"
    DISK = "DISK"
    DEPENDENCY = "DEPENDENCY"
    CODE_EXECUTION = "CODE_EXECUTION"
    SECURITY = "SECURITY"
    VALIDATION = "VALIDATION"
    DRIFT = "DRIFT"
    DEPLOYMENT = "DEPLOYMENT"
    UNKNOWN = "UNKNOWN"

class ErrorSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    RECOVERABLE = "RECOVERABLE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    SECURITY_CRITICAL = "SECURITY_CRITICAL"

class RecoveryDecisionState(str, Enum):
    RECOVERED = "RECOVERED"
    RETRY_REQUIRED = "RETRY_REQUIRED"
    FALLBACK_USED = "FALLBACK_USED"
    ROLLED_BACK = "ROLLED_BACK"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    SAFE_STOP = "SAFE_STOP"
    UNRECOVERABLE = "UNRECOVERABLE"
    SECURITY_STOP = "SECURITY_STOP"

class CircuitBreakerState(str, Enum):
    CLOSED = "CLOSED"
    OPEN = "OPEN"
    HALF_OPEN = "HALF_OPEN"

class ErrorCode(str, Enum):
    ERR_DATA_INVALID = "ERR_DATA_INVALID"
    ERR_SCHEMA_MISMATCH = "ERR_SCHEMA_MISMATCH"
    ERR_DATABASE_CONNECTION = "ERR_DATABASE_CONNECTION"
    ERR_DATABASE_PERMISSION = "ERR_DATABASE_PERMISSION"
    ERR_RATE_LIMIT = "ERR_RATE_LIMIT"
    ERR_LLM_TIMEOUT = "ERR_LLM_TIMEOUT"
    ERR_LLM_QUOTA = "ERR_LLM_QUOTA"
    ERR_MCP_UNAVAILABLE = "ERR_MCP_UNAVAILABLE"
    ERR_PREPROCESSING_FAILED = "ERR_PREPROCESSING_FAILED"
    ERR_FEATURE_ENGINEERING_FAILED = "ERR_FEATURE_ENGINEERING_FAILED"
    ERR_MODEL_TRAINING_FAILED = "ERR_MODEL_TRAINING_FAILED"
    ERR_MODEL_VALIDATION_FAILED = "ERR_MODEL_VALIDATION_FAILED"
    ERR_MODEL_SERIALIZATION_FAILED = "ERR_MODEL_SERIALIZATION_FAILED"
    ERR_DEPLOYMENT_FAILED = "ERR_DEPLOYMENT_FAILED"
    ERR_DRIFT_DETECTED = "ERR_DRIFT_DETECTED"
    ERR_RESOURCE_LIMIT = "ERR_RESOURCE_LIMIT"
    ERR_SECURITY_BLOCKED = "ERR_SECURITY_BLOCKED"
    ERR_RECOVERY_FAILED = "ERR_RECOVERY_FAILED"
    ERR_UNKNOWN = "ERR_UNKNOWN"

# Categories that are safe for automatic exponential-backoff retries
RETRYABLE_CATEGORIES: Set[ErrorCategory] = {
    ErrorCategory.TRANSIENT,
    ErrorCategory.RATE_LIMIT,
    ErrorCategory.NETWORK,
    ErrorCategory.TIMEOUT,
    ErrorCategory.LLM_TIMEOUT,
    ErrorCategory.STREAM_FAILURE,
}

# Categories requiring pipeline strategy modification rather than blind retries
ADAPTIVE_RECOVERY_CATEGORIES: Set[ErrorCategory] = {
    ErrorCategory.DATA_FORMAT,
    ErrorCategory.DATA_QUALITY,
    ErrorCategory.MISSING_VALUE,
    ErrorCategory.FEATURE_ENGINEERING,
    ErrorCategory.MODEL_TRAINING,
    ErrorCategory.MODEL_SERIALIZATION,
    ErrorCategory.RESOURCE_EXHAUSTION,
    ErrorCategory.MEMORY,
    ErrorCategory.LLM_PROVIDER,
    ErrorCategory.LLM_QUOTA,
    ErrorCategory.MCP_FAILURE,
}

# Categories strictly demanding immediate security stop
SECURITY_HALT_CATEGORIES: Set[ErrorCategory] = {
    ErrorCategory.SECURITY,
    ErrorCategory.AUTHENTICATION,
    ErrorCategory.AUTHORIZATION,
}
