"""
DataWise AI — LLM Prompts Module
"""

from .system_prompts import (
    SUPERVISOR_SYSTEM_PROMPT,
    DATASET_INTERPRETATION_PROMPT,
    PREPROCESSING_STRATEGY_PROMPT,
    MODEL_SELECTION_PROMPT,
    EXPLAINABILITY_PROMPT,
    REPORT_GENERATION_PROMPT,
)

__all__ = [
    "SUPERVISOR_SYSTEM_PROMPT",
    "DATASET_INTERPRETATION_PROMPT",
    "PREPROCESSING_STRATEGY_PROMPT",
    "MODEL_SELECTION_PROMPT",
    "EXPLAINABILITY_PROMPT",
    "REPORT_GENERATION_PROMPT",
]
